version: '3.9'

services:
  db:
    image: postgres
    ports:
      - '15432:5432'
    environment:
      - POSTGRES_DB=pullnotifier
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - PGDATA=/data/postgres
    volumes:
      - postgres_data:/data/postgres
    command: postgres -c log_destination=stderr -c log_statement=all -c log_connections=on -c log_disconnections=on
    networks:
      - default
      - shared_network
    logging:
      options:
        max-size: '10k'
        max-file: '5'

  backend:
    build:
      context: ./
      dockerfile: Dockerfile.local
    environment:
      NODE_ENV: development
    ports:
      - '10000:3000'
      - '9229:9229'
    volumes:
      # Mount current dir into docker container
      - .:/home/node/app
      # Ignore local node_modules, use container
      - /home/node/app/node_modules
    command: sh -c 'npm run prisma:generate; npm run start:debug'
    env_file:
      - .env.docker
    networks:
      - default
      - shared_network
    tty: true

networks:
  shared_network:
    external: true

volumes:
  postgres_data:
    driver: local
