openapi: 3.0.1
info:
  title: Pull Notifier
  description: 'API docs'
  contact:
    email: me@ngockhuong.com
  version: 1.0.0
servers:
  - url: /
tags:
  - name: webhook
    description: webhook API
paths:
  /webhook/github/:key:
    post:
      tags:
        - webhook
      summary: Github webhook
      responses:
        200:
          description: OK
          content: {}
        400:
          description: Bad Request
          content: {}
        409:
          description: Conflict
          content: {}
        500:
          description: Server Error
          content: {}
